name: Gen3 Integration Tests

on: pull_request

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:
  integration_tests:
    name: Integration tests
    uses: paulineribeyre/funnel/.github/workflows/gen3_tests_main.yaml@ci
    with:
      SERVICE_TO_TEST: gen3_workflow
      RUN_IN_LOCAL_KIND_CLUSTER: "true"
      TEST_REPO_BRANCH: support-kind

